WITH joined_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
sales_by_ym  AS (
    SELECT
        YEAR(SALES_DATE) YEAR,
        MONTH(SALES_DATE) MONTH,
        USER_ID
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM joined_2021)
)
SELECT
    s.YEAR, s.MONTH, COUNT(DISTINCT s.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT s.USER_ID)/(SELECT COUNT(*) FROM joined_2021), 1) PUCHASED_RATIO
FROM sales_by_ym s
GROUP BY s.YEAR, s.MONTH
ORDER BY s.YEAR, s.MONTH;