SELECT f.FLAVOR FROM FIRST_HALF AS f
LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_SUM
    FROM JULY
    GROUP BY FLAVOR
) j ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + COALESCE(j.JULY_SUM, 0))
DESC
LIMIT 3;